import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import NavBar from './NavBar';
import { Box, Container } from '@mui/material';
import Providers from './ReduxProviders';
import { SessionProvider } from 'next-auth/react';
import AuthProvider from './auth/Provider';
import Spacer from '../component/Spacer';
import MathjaxProvider from '../component/MathjaxProvider';
import Head from 'next/head'

const inter = Inter({
  subsets: ['latin'],
  variable: "--font-inter"
})

export const metadata: Metadata = {
  title: 'Issue Apps',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="en">
      <Head>
        <script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"> </script >
      </Head>
      <body style={{ height: "100vh", padding: 0, margin: 0 }}>
        <MathjaxProvider>
          <AuthProvider>
            <Providers>
              <Box sx={{
                "& .MuiButtonBase-root": {
                  textTransform: "none"
                }
              }}>
                <NavBar />
                <div style={{ height: "calc(100vh - 42px)" }}>
                  <Spacer />
                  <div className={inter.variable}>{children}</div>
                </div>
              </Box>
            </Providers>
          </AuthProvider>
        </MathjaxProvider>
      </body>
    </html>
  )
}
