import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import NavBar from './NavBar';
import Spacer from '@/component/Spacer';
import { Container } from '@mui/material';

const inter = Inter({
  subsets: ['latin'],
  variable: "--font-inter"
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{ height: "100vh", padding: 0, margin: 0 }}>
        <div >
          <NavBar />
          <div style={{ height: "calc(100vh - 42px)" }}>
            <Container>
              <Spacer />
              <div className={inter.variable}>{children}</div>
            </Container>
          </div>
        </div>

      </body>
    </html>
  )
}
